export const countryCodes = [
	{ countryCode:'AD', 'name': 'ANDORRA','code': '376' },
	{ countryCode:'AE', 'name': 'UNITED ARAB EMIRATES','code': '971'},
	{ countryCode:'AF', 'name': 'AFGHANISTAN','code': '93' },
	{ countryCode:'AG', 'name': 'ANTIGUA AND BARBUDA','code': '1268' },
	{ countryCode:'AI', 'name': 'ANGUILLA','code': '1264'},
	{ countryCode:'AL', 'name': 'ALBANIA','code': '355'} ,
	{ countryCode:'AM', 'name': 'ARMENIA','code': '374'} ,
	{ countryCode:'AN', 'name': 'NETHERLANDS ANTILLES','code': '599'},
	{ countryCode:'AO', 'name': 'ANGOLA','code': '244'} ,
	{ countryCode:'AQ', 'name': 'ANTARCTICA','code': '672'} ,
	{ countryCode:'AR', 'name': 'ARGENTINA','code': '54'} ,
	{ countryCode:'AS', 'name': 'AMERICAN SAMOA','code': '1684'} ,
	{ countryCode:'AT', 'name': 'AUSTRIA','code': '43'} ,
	{ countryCode:'AU', 'name': 'AUSTRALIA','code': '61'} ,
	{ countryCode:'AW', 'name': 'ARUBA','code': '297'} ,
	{ countryCode:'AZ', 'name': 'AZERBAIJAN','code': '994'} ,
	{ countryCode:'BA', 'name': 'BOSNIA AND HERZEGOVINA','code': '387'} ,
	{ countryCode:'BB', 'name': 'BARBADOS','code': '1246'} ,
	{ countryCode:'BD', 'name': 'BANGLADESH','code': '880'} ,
	{ countryCode:'BE', 'name': 'BELGIUM','code': '32'} ,
	{ countryCode:'BF', 'name': 'BURKINA FASO','code': '226'} ,
	{ countryCode:'BG', 'name': 'BULGARIA','code': '359'} ,
	{ countryCode:'BH', 'name': 'BAHRAIN','code': '973'} ,
	{ countryCode:'BI', 'name': 'BURUNDI','code': '257'} ,
	{ countryCode:'BJ', 'name': 'BENIN','code': '229'} ,
	{ countryCode:'BL', 'name': 'SAINT BARTHELEMY','code': '590'},
	{ countryCode:'BM', 'name': 'BERMUDA','code': '1441'} ,
	{ countryCode:'BN', 'name': 'BRUNEI DARUSSALAM','code': '673'} ,
	{ countryCode:'BO', 'name': 'BOLIVIA','code': '591'} ,
	{ countryCode:'BR', 'name': 'BRAZIL','code': '55'} ,
	{ countryCode:'BS', 'name': 'BAHAMAS','code': '1242'},
	{ countryCode:'BT', 'name': 'BHUTAN','code': '975'} ,
	{ countryCode:'BW', 'name': 'BOTSWANA','code': '267'} ,
	{ countryCode:'BY', 'name': 'BELARUS','code': '375'} ,
	{ countryCode:'BZ', 'name': 'BELIZE','code': '501'} ,
	{ countryCode:'CA', 'name': 'CANADA','code': '1'} ,
	{ countryCode:'CC', 'name': 'COCOS (KEELING) ISLANDS','code': '61'} ,
	{ countryCode:'CD', 'name': 'CONGO, THE DEMOCRATIC REPUBLIC OF THE','code': '243'} ,
	{ countryCode:'CF', 'name': 'CENTRAL AFRICAN REPUBLIC','code': '236'} ,
	{ countryCode:'CG', 'name': 'CONGO','code': '242'} ,
	{ countryCode:'CH', 'name': 'SWITZERLAND','code': '41'} ,
	{ countryCode:'CI', 'name': 'COTE D IVOIRE','code': '225'} ,
	{ countryCode:'CK', 'name': 'COOK ISLANDS','code': '682'} ,
	{ countryCode:'CL', 'name': 'CHILE','code': '56'} ,
	{ countryCode:'CM', 'name': 'CAMEROON','code': '237'} ,
	{ countryCode:'CN', 'name': 'CHINA','code': '86'} ,
	{ countryCode:'CO', 'name': 'COLOMBIA','code': '57'} ,
	{ countryCode:'CR', 'name': 'COSTA RICA','code': '506'} ,
	{ countryCode:'CU', 'name': 'CUBA','code': '53'} ,
	{ countryCode:'CV', 'name': 'CAPE VERDE','code': '238'} ,
	{ countryCode:'CX', 'name': 'CHRISTMAS ISLAND','code': '61'} ,
	{ countryCode:'CY', 'name': 'CYPRUS','code': '357'} ,
	{ countryCode:'CZ', 'name': 'CZECH REPUBLIC','code': '420'} ,
	{ countryCode:'DE', 'name': 'GERMANY','code': '49'} ,
	{ countryCode:'DJ', 'name': 'DJIBOUTI','code': '253'} ,
	{ countryCode:'DK', 'name': 'DENMARK','code': '45'} ,
	{ countryCode:'DM', 'name': 'DOMINICA','code': '1767'} ,
	{ countryCode:'DO', 'name': 'DOMINICAN REPUBLIC','code': '1809'} ,
	{ countryCode:'DZ', 'name': 'ALGERIA','code': '213'} ,
	{ countryCode:'EC', 'name': 'ECUADOR','code': '593'} ,
	{ countryCode:'EE', 'name': 'ESTONIA','code': '372'} ,
	{ countryCode:'EG', 'name': 'EGYPT','code': '20'} ,
	{ countryCode:'ER', 'name': 'ERITREA','code': '291'} ,
	{ countryCode:'ES', 'name': 'SPAIN','code': '34'} ,
	{ countryCode:'ET', 'name': 'ETHIOPIA','code': '251'} ,
	{ countryCode:'FI', 'name': 'FINLAND','code': '358'} ,
	{ countryCode:'FJ', 'name': 'FIJI','code': '679'} ,
	{ countryCode:'FK', 'name': 'FALKLAND ISLANDS (MALVINAS)','code': '500'} ,
	{ countryCode:'FM', 'name': 'MICRONESIA, FEDERATED STATES OF','code': '691'} ,
	{ countryCode:'FO', 'name': 'FAROE ISLANDS','code': '298'} ,
	{ countryCode:'FR', 'name': 'FRANCE','code': '33'} ,
	{ countryCode:'GA', 'name': 'GABON','code': '241'} ,
	{ countryCode:'GB', 'name': 'UNITED KINGDOM','code': '44'} ,
	{ countryCode:'GD', 'name': 'GRENADA','code': '1473'} ,
	{ countryCode:'GE', 'name': 'GEORGIA','code': '995'} ,
	{ countryCode:'GH', 'name': 'GHANA','code': '233'} ,
	{ countryCode:'GI', 'name': 'GIBRALTAR','code': '350'} ,
	{ countryCode:'GL', 'name': 'GREENLAND','code': '299'} ,
	{ countryCode:'GM', 'name': 'GAMBIA','code': '220'} ,
	{ countryCode:'GN', 'name': 'GUINEA','code': '224'},
	{ countryCode:'GQ', 'name': 'EQUATORIAL GUINEA','code': '240'} ,
	{ countryCode:'GR', 'name': 'GREECE','code': '30'} ,
	{ countryCode:'GT', 'name': 'GUATEMALA','code': '502'} ,
	{ countryCode:'GU', 'name': 'GUAM','code': '1671'} ,
	{ countryCode:'GW', 'name': 'GUINEA-BISSAU','code': '245'},
	{ countryCode:'GY', 'name': 'GUYANA','code': '592'},
	{ countryCode:'HK', 'name': 'HONG KONG','code': '852'},
	{ countryCode:'HN', 'name': 'HONDURAS','code': '504'},
	{ countryCode:'HR', 'name': 'CROATIA','code': '385'},
	{ countryCode:'HT', 'name': 'HAITI','code': '509'},
	{ countryCode:'HU', 'name': 'HUNGARY','code': '36'},
	{ countryCode:'ID', 'name': 'INDONESIA','code': '62'},
	{ countryCode:'IE', 'name': 'IRELAND','code': '353'},
	{ countryCode:'IL', 'name': 'ISRAEL','code': '972'},
	{ countryCode:'IM', 'name': 'ISLE OF MAN','code': '44'},
	{ countryCode:'IN', 'name': 'INDIA','code': '91'},
	{ countryCode:'IQ', 'name': 'IRAQ','code': '964'},
	{ countryCode:'IR', 'name': 'IRAN, ISLAMIC REPUBLIC OF','code': '98'},
	{ countryCode:'IS', 'name': 'ICELAND','code': '354'} ,
	{ countryCode:'IT', 'name': 'ITALY','code': '39'} ,
	{ countryCode:'JM', 'name': 'JAMAICA','code': '1876'} ,
	{ countryCode:'JO', 'name': 'JORDAN','code': '962'} ,
	{ countryCode:'JP', 'name': 'JAPAN','code': '81'} ,
	{ countryCode:'KE', 'name': 'KENYA','code': '254'} ,
	{ countryCode:'KG', 'name': 'KYRGYZSTAN','code': '996'} ,
	{ countryCode:'KH', 'name': 'CAMBODIA','code': '855'} ,
	{ countryCode:'KI', 'name': 'KIRIBATI','code': '686'} ,
	{ countryCode:'KM', 'name': 'COMOROS','code': '269'} ,
	{ countryCode:'KN', 'name': 'SAINT KITTS AND NEVIS','code': '1869'} ,
	{ countryCode:'KP', 'name': 'KOREA DEMOCRATIC PEOPLES REPUBLIC OF','code': '850'} ,
	{ countryCode:'KR', 'name': 'KOREA REPUBLIC OF','code': '82'} ,
	{ countryCode:'KW', 'name': 'KUWAIT','code': '965'} ,
	{ countryCode:'KY', 'name': 'CAYMAN ISLANDS','code': '1345'} ,
	{ countryCode:'KZ', 'name': 'KAZAKSTAN','code': '7'} ,
	{ countryCode:'LA', 'name': 'LAO PEOPLES DEMOCRATIC REPUBLIC','code': '856'} ,
	{ countryCode:'LB', 'name': 'LEBANON','code': '961'} ,
	{ countryCode:'LC', 'name': 'SAINT LUCIA','code': '1758'} ,
	{ countryCode:'LI', 'name': 'LIECHTENSTEIN','code': '423'} ,
	{ countryCode:'LK', 'name': 'SRI LANKA','code': '94'} ,
	{ countryCode:'LR', 'name': 'LIBERIA','code': '231'} ,
	{ countryCode:'LS', 'name': 'LESOTHO','code': '266'} ,
	{ countryCode:'LT', 'name': 'LITHUANIA','code': '370'} ,
	{ countryCode:'LU', 'name': 'LUXEMBOURG','code': '352'} ,
	{ countryCode:'LV', 'name': 'LATVIA','code': '371'} ,
	{ countryCode:'LY', 'name': 'LIBYAN ARAB JAMAHIRIYA','code': '218'} ,
	{ countryCode:'MA', 'name': 'MOROCCO','code': '212'} ,
	{ countryCode:'MC', 'name': 'MONACO','code': '377'} ,
	{ countryCode:'MD', 'name': 'MOLDOVA, REPUBLIC OF','code': '373'} ,
	{ countryCode:'ME', 'name': 'MONTENEGRO','code': '382'},
	{ countryCode:'MF', 'name': 'SAINT MARTIN','code': '1599'} ,
	{ countryCode:'MG', 'name': 'MADAGASCAR','code': '261'},
	{ countryCode:'MH', 'name': 'MARSHALL ISLANDS','code': '692'},
	{ countryCode:'MK', 'name': 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF','code': '389'},
	{ countryCode:'ML', 'name': 'MALI','code': '223'},
	{ countryCode:'MM', 'name': 'MYANMAR','code': '95'},
	{ countryCode:'MN', 'name': 'MONGOLIA','code': '976'},
	{ countryCode:'MO', 'name': 'MACAU','code': '853'},
	{ countryCode:'MP', 'name': 'NORTHERN MARIANA ISLANDS','code': '1670'},
	{ countryCode:'MR', 'name': 'MAURITANIA','code': '222'},
	{ countryCode:'MS', 'name': 'MONTSERRAT','code': '1664'},
	{ countryCode:'MT', 'name': 'MALTA','code': '356'},
	{ countryCode:'MU', 'name': 'MAURITIUS','code': '230'},
	{ countryCode:'MV', 'name': 'MALDIVES','code': '960'},
	{ countryCode:'MW', 'name': 'MALAWI','code': '265'},
	{ countryCode:'MX', 'name': 'MEXICO','code': '52'} ,
	{ countryCode:'MY', 'name': 'MALAYSIA','code': '60'},
	{ countryCode:'MZ', 'name': 'MOZAMBIQUE','code': '258'},
	{ countryCode:'NA', 'name': 'NAMIBIA','code': '264'},
	{ countryCode:'NC', 'name': 'NEW CALEDONIA','code': '687'},
	{ countryCode:'NE', 'name': 'NIGER','code': '227'},
	{ countryCode:'NG', 'name': 'NIGERIA','code': '234'},
	{ countryCode:'NI', 'name': 'NICARAGUA','code': '505'},
	{ countryCode:'NL', 'name': 'NETHERLANDS','code': '31'},
	{ countryCode:'NO', 'name': 'NORWAY','code': '47'},
	{ countryCode:'NP', 'name': 'NEPAL','code': '977'},
	{ countryCode:'NR', 'name': 'NAURU','code': '674'},
	{ countryCode:'NU', 'name': 'NIUE','code': '683'},
	{ countryCode:'NZ', 'name': 'NEW ZEALAND','code': '64'} ,
	{ countryCode:'OM', 'name': 'OMAN','code': '968'},
	{ countryCode:'PA', 'name': 'PANAMA','code': '507'} ,
	{ countryCode:'PE', 'name': 'PERU','code': '51'} ,
	{ countryCode:'PF', 'name': 'FRENCH POLYNESIA','code': '689'} ,
	{ countryCode:'PG', 'name': 'PAPUA NEW GUINEA','code': '675'} ,
	{ countryCode:'PH', 'name': 'PHILIPPINES','code': '63'} ,
	{ countryCode:'PK', 'name': 'PAKISTAN','code': '92'} ,
	{ countryCode:'PL', 'name': 'POLAND','code': '48'} ,
	{ countryCode:'PM', 'name': 'SAINT PIERRE AND MIQUELON','code': '508'} ,
	{ countryCode:'PN', 'name': 'PITCAIRN','code': '870'} ,
	{ countryCode:'PR', 'name': 'PUERTO RICO','code': '1'} ,
	{ countryCode:'PT', 'name': 'PORTUGAL','code': '351'} ,
	{ countryCode:'PW', 'name': 'PALAU','code': '680'} ,
	{ countryCode:'PY', 'name': 'PARAGUAY','code': '595'} ,
	{ countryCode:'QA', 'name': 'QATAR','code': '974'},
	{ countryCode:'RO', 'name': 'ROMANIA','code': '40'} ,
	{ countryCode:'RS', 'name': 'SERBIA','code': '381'} ,
	{ countryCode:'RU', 'name': 'RUSSIAN FEDERATION','code': '7'} ,
	{ countryCode:'RW', 'name': 'RWANDA','code': '250'} ,
	{ countryCode:'SA', 'name': 'SAUDI ARABIA','code': '966'} ,
	{ countryCode:'SB', 'name': 'SOLOMON ISLANDS','code': '677'} ,
	{ countryCode:'SC', 'name': 'SEYCHELLES','code': '248'} ,
	{ countryCode:'SD', 'name': 'SUDAN','code': '249'} ,
	{ countryCode:'SE', 'name': 'SWEDEN','code': '46'} ,
	{ countryCode:'SG', 'name': 'SINGAPORE','code': '65'} ,
	{ countryCode:'SH', 'name': 'SAINT HELENA','code': '290'} ,
	{ countryCode:'SI', 'name': 'SLOVENIA','code': '386'} ,
	{ countryCode:'SK', 'name': 'SLOVAKIA','code': '421'} ,
	{ countryCode:'SL', 'name': 'SIERRA LEONE','code': '232'} ,
	{ countryCode:'SM', 'name': 'SAN MARINO','code': '378'} ,
	{ countryCode:'SN', 'name': 'SENEGAL','code': '221'} ,
	{ countryCode:'SO', 'name': 'SOMALIA','code': '252'} ,
	{ countryCode:'SR', 'name': 'SURINAME','code': '597'} ,
	{ countryCode:'ST', 'name': 'SAO TOME AND PRINCIPE','code': '239'} ,
	{ countryCode:'SV', 'name': 'EL SALVADOR','code': '503'} ,
	{ countryCode:'SY', 'name': 'SYRIAN ARAB REPUBLIC','code': '963'} ,
	{ countryCode:'SZ', 'name': 'SWAZILAND','code': '268'} ,
	{ countryCode:'TC', 'name': 'TURKS AND CAICOS ISLANDS','code': '1649'} ,
	{ countryCode:'TD', 'name': 'CHAD','code': '235'} ,
	{ countryCode:'TG', 'name': 'TOGO','code': '228'} ,
	{ countryCode:'TH', 'name': 'THAILAND','code': '66'} ,
	{ countryCode:'TJ', 'name': 'TAJIKISTAN','code': '992'} ,
	{ countryCode:'TK', 'name': 'TOKELAU','code': '690'} ,
	{ countryCode:'TL', 'name': 'TIMOR-LESTE','code': '670'} ,
	{ countryCode:'TM', 'name': 'TURKMENISTAN','code': '993'} ,
	{ countryCode:'TN', 'name': 'TUNISIA','code': '216'} ,
	{ countryCode:'TO', 'name': 'TONGA','code': '676'} ,
	{ countryCode:'TR', 'name': 'TURKEY','code': '90'} ,
	{ countryCode:'TT', 'name': 'TRINIDAD AND TOBAGO','code': '1868'} ,
	{ countryCode:'TV', 'name': 'TUVALU','code': '688'} ,
	{ countryCode:'TW', 'name': 'TAIWAN, PROVINCE OF CHINA','code': '886'} ,
	{ countryCode:'TZ', 'name': 'TANZANIA, UNITED REPUBLIC OF','code': '255'} ,
	{ countryCode:'UA', 'name': 'UKRAINE','code': '380'} ,
	{ countryCode:'UG', 'name': 'UGANDA','code': '256'} ,
	{ countryCode:'US', 'name': 'UNITED STATES','code': '1'} ,
	{ countryCode:'UY', 'name': 'URUGUAY','code': '598'} ,
	{ countryCode:'UZ', 'name': 'UZBEKISTAN','code': '998'} ,
	{ countryCode:'VA', 'name': 'HOLY SEE (VATICAN CITY STATE)','code': '39'} ,
	{ countryCode:'VC', 'name': 'SAINT VINCENT AND THE GRENADINES','code': '1784'} ,
	{ countryCode:'VE', 'name': 'VENEZUELA','code': '58'} ,
	{ countryCode:'VG', 'name': 'VIRGIN ISLANDS, BRITISH','code': '1284'} ,
	{ countryCode:'VI', 'name': 'VIRGIN ISLANDS, U.S.','code': '1340'} ,
	{ countryCode:'VN', 'name': 'VIET NAM','code': '84'} ,
	{ countryCode:'VU', 'name': 'VANUATU','code': '678'} ,
	{ countryCode:'WF', 'name': 'WALLIS AND FUTUNA','code': '681' },
	{ countryCode:'WS', 'name': 'SAMOA','code': '685'} ,
	{ countryCode:'XK', 'name': 'KOSOVO','code': '381'} ,
	{ countryCode:'YE', 'name': 'YEMEN','code': '967'} ,
	{ countryCode:'YT', 'name': 'MAYOTTE','code': '262'} ,
	{ countryCode:'ZA', 'name': 'SOUTH AFRICA','code': '27'} ,
	{ countryCode:'ZM', 'name': 'ZAMBIA','code': '260'} ,
	{ countryCode:'ZW', 'name': 'ZIMBABWE','code': '263'} 
];